### ISSUE TITLE
error with the data type

### ISSUE THREAD

**Issue by zhaojw219** [pascal1129/airbus_rle_to_coco#2]
when I do "python 1_ships_to_coco.py",I had an error with the data type like this:
Traceback (most recent call last):
  File "1_ships_to_coco.py", line 149, in <module>
    main()
  File "1_ships_to_coco.py", line 124, in main
    binary_mask = rle_decode(rle_masks[index])
  File "1_ships_to_coco.py", line 52, in rle_decode
    s = mask_rle.split()
AttributeError: 'float' object has no attribute 'split'
I have tried many solutions,but I can not solve it.please help me.Thank you.

**Comment by pascal1129** [comment]
It means that tensor 'mask_rle' is not a string list, which can be caused by many problems. My suggestion is that you can print the tensor information , such as shape, dtype and so on. It is quite useful in mots of time.

**Comment by zhaojw219** [comment]
Thank you very much!I will try.




------------------ 原始邮件 ------------------
发件人: "Pascal"<notifications@github.com>;
发送时间: 2019年5月4日(星期六) 晚上6:15
收件人: "pascal1129/kaggle_airbus_ship_detection"<kaggle_airbus_ship_detection@noreply.github.com>;
抄送: "852755528"<852755528@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [pascal1129/kaggle_airbus_ship_detection] error with the datatype (#2)




It means that tensor 'mask_rle' is not a string list, which can be caused by many problems. My suggestion is that you can print the tensor information , such as shape, dtype and so on. It is quite useful in mots of time.
